/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppCliente.vista;


import AppCliente.conexion.Client;
import general.Peticion;
import general.TipoAccion;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author ersolano
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form FrmSaludo
     */
    

    public static JPanel last;
    
    private PanelMenuInicial menuInicial;
    
    public MainWindow() {
        initComponents();
        
        imgAdmin.setIcon(Utilities.loadResizeIcon("src\\img\\admin.png", 150));
        imgCliente.setIcon(Utilities.loadResizeIcon("src\\img\\cliente.png", 150));        
        imgLogo.setIcon(Utilities.loadResizeIcon("src\\img\\LOGO.png", 350));  
        
        menuInicial = new PanelMenuInicial(usefulPanel, contentPanel);
        
        cargarPanel(menuInicial);
    }
    

    public void cargarPanel(JPanel panel) {
        last = (JPanel)contentPanel.getComponent(0);
        contentPanel.removeAll();
        contentPanel.add(panel);
        contentPanel.repaint();
        contentPanel.revalidate();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        usefulPanel = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();
        chooseAnOptionPanel = new javax.swing.JPanel();
        btnClient = new javax.swing.JPanel();
        imgCliente = new javax.swing.JLabel();
        lbSismos15 = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JPanel();
        imgAdmin = new javax.swing.JLabel();
        lbSismos13 = new javax.swing.JLabel();
        lbSismos14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1360, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1700, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPanel.setBackground(new java.awt.Color(86, 73, 64));
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO.png"))); // NOI18N
        topPanel.add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 220));

        usefulPanel.setBackground(new java.awt.Color(86, 73, 64));
        usefulPanel.setLayout(new java.awt.CardLayout());
        topPanel.add(usefulPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 330, 650));

        getContentPane().add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 900));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setPreferredSize(new java.awt.Dimension(1350, 900));
        contentPanel.setLayout(new java.awt.CardLayout());

        chooseAnOptionPanel.setBackground(new java.awt.Color(255, 255, 255));
        chooseAnOptionPanel.setPreferredSize(new java.awt.Dimension(1350, 680));
        chooseAnOptionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClient.setBackground(new java.awt.Color(212, 212, 212));
        btnClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientMouseClicked(evt);
            }
        });
        btnClient.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin.png"))); // NOI18N
        imgCliente.setLabelFor(imgAdmin);
        imgCliente.setToolTipText("");
        imgCliente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        imgCliente.setIconTextGap(2);
        imgCliente.setPreferredSize(new java.awt.Dimension(500, 500));
        btnClient.add(imgCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 150, 150));

        lbSismos15.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos15.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbSismos15.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos15.setText("Cliente");
        lbSismos15.setToolTipText("");
        btnClient.add(lbSismos15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 80, 40));

        chooseAnOptionPanel.add(btnClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 190, 250, 250));

        btnAdmin.setBackground(new java.awt.Color(212, 212, 212));
        btnAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminMouseClicked(evt);
            }
        });
        btnAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin.png"))); // NOI18N
        imgAdmin.setLabelFor(imgAdmin);
        imgAdmin.setToolTipText("");
        imgAdmin.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        imgAdmin.setIconTextGap(2);
        imgAdmin.setPreferredSize(new java.awt.Dimension(500, 500));
        btnAdmin.add(imgAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 150, 150));

        lbSismos13.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos13.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbSismos13.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos13.setText("Admin");
        lbSismos13.setToolTipText("");
        btnAdmin.add(lbSismos13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 70, 40));

        chooseAnOptionPanel.add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 250, 250));

        lbSismos14.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos14.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        lbSismos14.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos14.setText("Choose an option");
        lbSismos14.setToolTipText("");
        chooseAnOptionPanel.add(lbSismos14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 280, 40));

        contentPanel.add(chooseAnOptionPanel, "card2");

        getContentPane().add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 1350, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_btnAdminMouseClicked

    private void btnClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnClientMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAdmin;
    private javax.swing.JPanel btnClient;
    private javax.swing.JPanel chooseAnOptionPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel imgAdmin;
    private javax.swing.JLabel imgCliente;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel lbSismos13;
    private javax.swing.JLabel lbSismos14;
    private javax.swing.JLabel lbSismos15;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPanel usefulPanel;
    // End of variables declaration//GEN-END:variables
}
