/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppCliente.vista;

import AppCliente.conexion.Client;
import AppServidora.modelo.Alimento;
import AppServidora.modelo.Carrito;
import AppServidora.modelo.PMesa;
import AppServidora.modelo.Pedido;
import AppServidora.modelo.Producto;
import general.Peticion;
import general.TipoAccion;
import java.awt.GridBagConstraints;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author erksm
 */
public class PanelPedidoMesa extends javax.swing.JPanel {

    /**
     * Creates new form PanelPedidoMesa
     */
    private PMesa pMesa;
    private Carrito carrito;
    private JPanel contentPanel;
    private JPanel backPanel;
    private JPanel usefulPanel;
    private JPanel panelAcArgar;
    
    public PanelPedidoMesa(JPanel useful,JPanel content, JPanel back,Carrito carrito) {
        initComponents();        
        this.carrito = carrito;
        usefulPanel = useful;
        contentPanel = content; 
        backPanel = back;
        
        imgArrowLeft.setIcon(Utilities.loadResizeIcon("src\\img\\arrow-left.png", 50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void loadDatos(String nombre){
        Date fecha = new Date(System.currentTimeMillis());     
        pMesa = new PMesa(0,carrito, carrito.getTotalPrecio(), fecha,nombre);
        txtDesgloce.setText(pMesa.mostrarDesgloce());
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSismos14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesgloce = new javax.swing.JTextArea();
        txtMesa = new javax.swing.JTextField();
        lbSismos13 = new javax.swing.JLabel();
        btnOrdenar = new javax.swing.JLabel();
        imgArrowLeft = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbSismos14.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos14.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        lbSismos14.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos14.setText("En Sitio");
        lbSismos14.setToolTipText("");
        add(lbSismos14, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 140, 40));

        jPanel1.setBackground(new java.awt.Color(212, 212, 212));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 340, 10));

        jPanel2.setBackground(new java.awt.Color(86, 73, 64));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDesgloce.setEditable(false);
        txtDesgloce.setBackground(new java.awt.Color(86, 73, 64));
        txtDesgloce.setColumns(20);
        txtDesgloce.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtDesgloce.setForeground(new java.awt.Color(255, 255, 255));
        txtDesgloce.setRows(5);
        txtDesgloce.setText("asdfasdf");
        txtDesgloce.setToolTipText("");
        jScrollPane1.setViewportView(txtDesgloce);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 590, 450));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 630, 500));

        txtMesa.setBackground(new java.awt.Color(212, 212, 212));
        txtMesa.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtMesa.setForeground(new java.awt.Color(99, 99, 99));
        txtMesa.setBorder(null);
        jPanel1.add(txtMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 340, 30));

        lbSismos13.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos13.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbSismos13.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos13.setText("Mesa");
        lbSismos13.setToolTipText("");
        jPanel1.add(lbSismos13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 50, 30));

        btnOrdenar.setBackground(new java.awt.Color(86, 73, 64));
        btnOrdenar.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btnOrdenar.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdenar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnOrdenar.setText("Ordenar");
        btnOrdenar.setIconTextGap(20);
        btnOrdenar.setOpaque(true);
        btnOrdenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOrdenarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOrdenarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOrdenarMouseExited(evt);
            }
        });
        jPanel1.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 340, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 1210, 500));

        imgArrowLeft.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        imgArrowLeft.setForeground(new java.awt.Color(255, 255, 255));
        imgArrowLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO.png"))); // NOI18N
        imgArrowLeft.setText("<");
        imgArrowLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgArrowLeftMouseClicked(evt);
            }
        });
        add(imgArrowLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrdenarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrdenarMouseClicked
        // TODO add your handling code here:
        int mesa = 0;
        try{
            mesa = Integer.parseInt(txtMesa.getText());
            pMesa.setMesa(mesa);
            Peticion peticion = new Peticion(TipoAccion.AGREGAR_PEDIDO, pMesa);
            Client conexion = new Client(peticion);
            Object respuesta = conexion.getRespuestaServer();
            if(respuesta != null){
                if((boolean)respuesta){
                    JOptionPane.showMessageDialog(null, "Se ha registrado su pedido correctamente!", "Error", JOptionPane.INFORMATION_MESSAGE);
                    PanelMenuInicial nuevo = new PanelMenuInicial(usefulPanel, contentPanel);
                    Utilities.cargarPanel(contentPanel, nuevo);
                    
                }
                    
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hay datos Incorrectos!", "Error", JOptionPane.ERROR_MESSAGE);
        } 

        
    }//GEN-LAST:event_btnOrdenarMouseClicked

    private void btnOrdenarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrdenarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrdenarMouseEntered

    private void btnOrdenarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrdenarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrdenarMouseExited

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_formMouseEntered

    private void imgArrowLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgArrowLeftMouseClicked
        // TODO add your handling code here:
        Utilities.cargarPanel(contentPanel, backPanel);
    }//GEN-LAST:event_imgArrowLeftMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnOrdenar;
    private javax.swing.JLabel imgArrowLeft;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbSismos13;
    private javax.swing.JLabel lbSismos14;
    private javax.swing.JTextArea txtDesgloce;
    private javax.swing.JTextField txtMesa;
    // End of variables declaration//GEN-END:variables
}
