/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppCliente.vista;

import AppCliente.conexion.Client;
import AppServidora.modelo.Alimento;
import AppServidora.modelo.Constantes;
import AppServidora.modelo.Pedido;
import general.Peticion;
import general.TipoAccion;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author muril
 */
public class PanelAdminPedido extends javax.swing.JPanel {
    private JPanel contentPanel;
    private JPanel backPanel;

    /**
     * Creates new form PanelAdminPedido
     * @param content
     * @param back
     */
    public PanelAdminPedido(JPanel content, JPanel back) {
        initComponents();
        backPanel = back;
        contentPanel = content; 
        imgArrowLeft.setIcon(Utilities.loadResizeIcon("src\\img\\arrow-left.png", 50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void loadDatos(){

        Peticion peticion1 = new Peticion(TipoAccion.LOAD_CONST,"");
        Client conexion1 = new Client(peticion1);
        Object respuesta1 = conexion1.getRespuestaServer();
        if(respuesta1 != null){
            ArrayList array = (ArrayList)respuesta1;
            Constantes.setContantEmpaque((int)array.get(0));
            Constantes.setContanteEntrega((int)array.get(1));
        }
        Peticion peticion = new Peticion(TipoAccion.VER_PEDIDOS, "");
        Client conexion = new Client(peticion);     
        
        Object respuesta = conexion.getRespuestaServer();
        if(respuesta != null){
            tablePedidos.setModel((DefaultTableModel)respuesta);
            tablePedidos.setDefaultEditor(Object.class, null);
        }
        infoPedido.setText("");
        txtDesgloce.setText("");
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePedidos = new javax.swing.JTable();
        imgArrowLeft = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDesgloce = new javax.swing.JTextArea();
        lbSismos15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        infoPedido = new javax.swing.JTextArea();
        lbSismos17 = new javax.swing.JLabel();
        lbSismos16 = new javax.swing.JLabel();
        btnPagar = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablePedidos.setBackground(new java.awt.Color(255, 255, 255));
        tablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePedidos.setOpaque(false);
        tablePedidos.setSelectionBackground(new java.awt.Color(86, 73, 64));
        tablePedidos.setShowHorizontalLines(true);
        tablePedidos.setShowVerticalLines(true);
        tablePedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablePedidosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablePedidos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 1270, 280));

        imgArrowLeft.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        imgArrowLeft.setForeground(new java.awt.Color(255, 255, 255));
        imgArrowLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO.png"))); // NOI18N
        imgArrowLeft.setText("<");
        imgArrowLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgArrowLeftMouseClicked(evt);
            }
        });
        jPanel1.add(imgArrowLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel4.setBackground(new java.awt.Color(212, 212, 212));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(86, 73, 64));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDesgloce.setEditable(false);
        txtDesgloce.setBackground(new java.awt.Color(86, 73, 64));
        txtDesgloce.setColumns(20);
        txtDesgloce.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtDesgloce.setForeground(new java.awt.Color(255, 255, 255));
        txtDesgloce.setRows(5);
        txtDesgloce.setText("asdfasdf");
        txtDesgloce.setToolTipText("");
        jScrollPane4.setViewportView(txtDesgloce);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 590, 260));

        lbSismos15.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos15.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbSismos15.setForeground(new java.awt.Color(255, 255, 255));
        lbSismos15.setText("Carrito");
        lbSismos15.setToolTipText("");
        jPanel5.add(lbSismos15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 80, 30));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 630, 500));

        infoPedido.setEditable(false);
        infoPedido.setBackground(new java.awt.Color(212, 212, 212));
        infoPedido.setColumns(20);
        infoPedido.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        infoPedido.setForeground(new java.awt.Color(0, 0, 0));
        infoPedido.setRows(5);
        infoPedido.setToolTipText("");
        jScrollPane3.setViewportView(infoPedido);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 540, 260));

        lbSismos17.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos17.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbSismos17.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos17.setText("Pedido");
        lbSismos17.setToolTipText("");
        jPanel4.add(lbSismos17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 80, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 1210, 420));

        lbSismos16.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos16.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbSismos16.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos16.setText("Pago de pedidos");
        lbSismos16.setToolTipText("");
        jPanel1.add(lbSismos16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 190, 30));

        btnPagar.setBackground(new java.awt.Color(86, 73, 64));
        btnPagar.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btnPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnPagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPagar.setText("Pagar pedido");
        btnPagar.setIconTextGap(20);
        btnPagar.setOpaque(true);
        btnPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPagarMouseClicked(evt);
            }
        });
        jPanel1.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 830, 280, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1362, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void tablePedidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePedidosMousePressed
        // TODO add your handling code here:

        TableModel tableModel = tablePedidos.getModel();
        int codigo = (int) tableModel.getValueAt(tablePedidos.getSelectedRow(), 0);
        System.out.println("El codigo del pedido es: "+ codigo);
        Peticion peticion = new Peticion(TipoAccion.CONSULTAR_PEDIDO, codigo);
        Client conexion = new Client(peticion);

        Object respuesta = conexion.getRespuestaServer();
        if(respuesta != null){
            Pedido pedidoRespuesta = (Pedido)respuesta;
            txtDesgloce.setText(pedidoRespuesta.mostrarDesgloce());
            infoPedido.setText(pedidoRespuesta.toString());
        }

    }//GEN-LAST:event_tablePedidosMousePressed

    private void imgArrowLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgArrowLeftMouseClicked
        // TODO add your handling code here:
        Utilities.cargarPanel(contentPanel, backPanel);
    }//GEN-LAST:event_imgArrowLeftMouseClicked

    private void btnPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagarMouseClicked
        // TODO add your handling code here:
        TableModel tableModel = tablePedidos.getModel();
        int codigo = (int) tableModel.getValueAt(tablePedidos.getSelectedRow(), 0);
        Peticion peticion = new Peticion(TipoAccion.ELIMINAR_PEDIDO, codigo);
        Client conexion = new Client(peticion);

        Object respuesta = conexion.getRespuestaServer();
        if(respuesta != null){
            boolean answer = (boolean)respuesta;
            if(answer){
                JOptionPane.showMessageDialog(null, "Se ha pagado correctamente el pedido!", "Listo", JOptionPane.INFORMATION_MESSAGE);
                loadDatos();
            }else
                JOptionPane.showMessageDialog(null, "Hubo un problema al pagar el pedido!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPagarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnPagar;
    private javax.swing.JLabel imgArrowLeft;
    private javax.swing.JTextArea infoPedido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbSismos15;
    private javax.swing.JLabel lbSismos16;
    private javax.swing.JLabel lbSismos17;
    private javax.swing.JTable tablePedidos;
    private javax.swing.JTextArea txtDesgloce;
    // End of variables declaration//GEN-END:variables
}
