/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppCliente.vista;

import AppCliente.conexion.Client;
import general.Peticion;
import general.TipoAccion;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author muril
 */
public class PanelEstadisticaTopTen extends javax.swing.JPanel {

    /**
     * Creates new form PanelEstadisticaTopTen
     */
    
    private JPanel contentPanel;
    private JPanel backPanel;
    
    public PanelEstadisticaTopTen(JPanel content, JPanel back) {
        initComponents();
        backPanel = back;
        contentPanel = content; 
        imgArrowLeft.setIcon(Utilities.loadResizeIcon("src\\img\\arrow-left.png", 50));
    }
    public void loadDatos(){

        
        Peticion peticion = new Peticion(TipoAccion.TOP_TEN, "");
        Client conexion = new Client(peticion);     
        
        Object respuesta = conexion.getRespuestaServer();
        if(respuesta != null){
            tableAlimentos.setModel((DefaultTableModel)respuesta);
            tableAlimentos.setDefaultEditor(Object.class, null);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAlimentos = new javax.swing.JTable();
        imgArrowLeft = new javax.swing.JLabel();
        lbSismos14 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableAlimentos.setBackground(new java.awt.Color(255, 255, 255));
        tableAlimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAlimentos.setOpaque(false);
        tableAlimentos.setSelectionBackground(new java.awt.Color(86, 73, 64));
        tableAlimentos.setShowHorizontalLines(true);
        tableAlimentos.setShowVerticalLines(true);
        tableAlimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableAlimentosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableAlimentos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 1270, 280));

        imgArrowLeft.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        imgArrowLeft.setForeground(new java.awt.Color(255, 255, 255));
        imgArrowLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO.png"))); // NOI18N
        imgArrowLeft.setText("<");
        imgArrowLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgArrowLeftMouseClicked(evt);
            }
        });
        jPanel1.add(imgArrowLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        lbSismos14.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos14.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbSismos14.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos14.setText("Top 10 alimentos más solicitados");
        lbSismos14.setToolTipText("");
        jPanel1.add(lbSismos14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 360, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1362, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableAlimentosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAlimentosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableAlimentosMousePressed

    private void imgArrowLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgArrowLeftMouseClicked
        // TODO add your handling code here:
        Utilities.cargarPanel(contentPanel, backPanel);
    }//GEN-LAST:event_imgArrowLeftMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgArrowLeft;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbSismos14;
    private javax.swing.JTable tableAlimentos;
    // End of variables declaration//GEN-END:variables
}
