/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppCliente.vista;

import AppCliente.conexion.Client;
import AppServidora.modelo.Alimento;
import AppServidora.modelo.Carrito;
import AppServidora.modelo.Producto;
import AppServidora.modelo.TVisibilidad;
import general.Peticion;
import general.TipoAccion;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.MatteBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author erksm
 */
public class PanelClienteOrdenar extends javax.swing.JPanel {

    /**
     * Creates new form PanelClienteOrdenar
     */
    private JPanel contentPanel;
    private JPanel backPanel;
    private JPanel usefulPanel;
    private PanelCarrito carritoPanel;
    private PanelPedidoMenu pedidoMenuPanel;
    
    private Carrito carrito = new Carrito();
    
    public PanelClienteOrdenar(JPanel useful, JPanel content, JPanel back, PanelCarrito carrito) {
        usefulPanel = useful;
        contentPanel = content; 
        backPanel = back;
        carritoPanel = carrito;
        
        pedidoMenuPanel = new PanelPedidoMenu(carritoPanel,content, this, this.carrito);
        initComponents();

        imgArrowLeft.setIcon(Utilities.loadResizeIcon("src\\img\\arrow-left.png", 50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     public void cargarCampos(Alimento alimento) {
        txtCodigo.setText(alimento.getCodigo());
        txtNombre.setText(alimento.getNombre());
        txtDescripcion.setText(alimento.getDescripcion());       
        txtSizePorcion.setText(String.valueOf(alimento.getSizePorcion()));
        txtPiezas.setText(String.valueOf(alimento.getPiezasPorcion()));
        txtCalorias.setText(String.valueOf(alimento.getCaloriasPorcion()));
        //caloriasPieza = Integer.parseInt(txtSizePorcion.getText());
        txtPrecio.setText(String.valueOf(alimento.getPrecio()));
        imgAlimento.setIcon(Utilities.loadResizeIcon(alimento.getImg(), 250));        
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableAlimentos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txtCodigo = new javax.swing.JTextField();
        lbSismos12 = new javax.swing.JLabel();
        lbSismos14 = new javax.swing.JLabel();
        lbSismos15 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtSizePorcion = new javax.swing.JTextField();
        lbSismos16 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lbSismos17 = new javax.swing.JLabel();
        txtPiezas = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtCalorias = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        imgAlimento = new javax.swing.JLabel();
        lbSismos19 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lbSismos21 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JLabel();
        txtCantidadAgregar = new javax.swing.JTextField();
        lbSismos18 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        imgArrowLeft = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbSismos22 = new javax.swing.JLabel();
        cboTipoPlatillo = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JLabel();
        btnProcesarPedido = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableAlimentos.setBackground(new java.awt.Color(255, 255, 255));
        tableAlimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAlimentos.setOpaque(false);
        tableAlimentos.setSelectionBackground(new java.awt.Color(86, 73, 64));
        tableAlimentos.setShowHorizontalLines(true);
        tableAlimentos.setShowVerticalLines(true);
        tableAlimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableAlimentosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableAlimentos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 1270, 310));

        jPanel1.setBackground(new java.awt.Color(212, 212, 212));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 170, 10));

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(212, 212, 212));
        txtCodigo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(99, 99, 99));
        txtCodigo.setBorder(null);
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 190, 30));

        lbSismos12.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos12.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbSismos12.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos12.setText("Descripción:");
        lbSismos12.setToolTipText("");
        jPanel1.add(lbSismos12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 110, 30));

        lbSismos14.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos14.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbSismos14.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos14.setText("Código: ");
        lbSismos14.setToolTipText("");
        jPanel1.add(lbSismos14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 30));

        lbSismos15.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos15.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbSismos15.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos15.setText("Nombre: ");
        lbSismos15.setToolTipText("");
        jPanel1.add(lbSismos15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, 30));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(212, 212, 212));
        txtNombre.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(99, 99, 99));
        txtNombre.setBorder(null);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 190, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 170, 10));

        txtSizePorcion.setEditable(false);
        txtSizePorcion.setBackground(new java.awt.Color(212, 212, 212));
        txtSizePorcion.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtSizePorcion.setForeground(new java.awt.Color(99, 99, 99));
        txtSizePorcion.setBorder(null);
        jPanel1.add(txtSizePorcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 190, 30));

        lbSismos16.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos16.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbSismos16.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos16.setText("Tamaño Ración:");
        lbSismos16.setToolTipText("");
        jPanel1.add(lbSismos16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 80, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 170, 10));

        lbSismos17.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos17.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbSismos17.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos17.setText("Piezas:");
        lbSismos17.setToolTipText("");
        jPanel1.add(lbSismos17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 80, 30));

        txtPiezas.setEditable(false);
        txtPiezas.setBackground(new java.awt.Color(212, 212, 212));
        txtPiezas.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtPiezas.setForeground(new java.awt.Color(99, 99, 99));
        txtPiezas.setBorder(null);
        jPanel1.add(txtPiezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 190, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 170, 10));

        txtCalorias.setEditable(false);
        txtCalorias.setBackground(new java.awt.Color(212, 212, 212));
        txtCalorias.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtCalorias.setForeground(new java.awt.Color(99, 99, 99));
        txtCalorias.setBorder(null);
        jPanel1.add(txtCalorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 190, 30));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 170, 10));

        imgAlimento.setBackground(new java.awt.Color(0, 0, 0));
        imgAlimento.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        imgAlimento.setForeground(new java.awt.Color(0, 0, 0));
        imgAlimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/catalago/empty.png"))); // NOI18N
        imgAlimento.setText("IMG");
        imgAlimento.setToolTipText("");
        jPanel1.add(imgAlimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 250, 250));

        lbSismos19.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos19.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbSismos19.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos19.setText("Precio:");
        lbSismos19.setToolTipText("");
        jPanel1.add(lbSismos19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 80, 30));

        txtPrecio.setEditable(false);
        txtPrecio.setBackground(new java.awt.Color(212, 212, 212));
        txtPrecio.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(99, 99, 99));
        txtPrecio.setBorder(null);
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 190, 30));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 170, 10));

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtDescripcion);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 330, 150));

        lbSismos21.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos21.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbSismos21.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos21.setText("Calorías:");
        lbSismos21.setToolTipText("");
        jPanel1.add(lbSismos21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 80, 30));

        btnAgregar.setBackground(new java.awt.Color(86, 73, 64));
        btnAgregar.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregar.setText("Agregar");
        btnAgregar.setIconTextGap(20);
        btnAgregar.setOpaque(true);
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 330, 50));

        txtCantidadAgregar.setBackground(new java.awt.Color(212, 212, 212));
        txtCantidadAgregar.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtCantidadAgregar.setForeground(new java.awt.Color(99, 99, 99));
        txtCantidadAgregar.setText("1");
        txtCantidadAgregar.setBorder(null);
        jPanel1.add(txtCantidadAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 190, 30));

        lbSismos18.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos18.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbSismos18.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos18.setText("Cantidad a agregar");
        lbSismos18.setToolTipText("");
        jPanel1.add(lbSismos18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 170, 30));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 170, 10));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 1270, 300));

        imgArrowLeft.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        imgArrowLeft.setForeground(new java.awt.Color(255, 255, 255));
        imgArrowLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO.png"))); // NOI18N
        imgArrowLeft.setText("<");
        imgArrowLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgArrowLeftMouseClicked(evt);
            }
        });
        add(imgArrowLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel2.setBackground(new java.awt.Color(212, 212, 212));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbSismos22.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos22.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbSismos22.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos22.setText("Tipo de platillo:");
        lbSismos22.setToolTipText("");
        jPanel2.add(lbSismos22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, 30));

        cboTipoPlatillo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Fuerte", "Entrada", "Postre", "Bebida" }));
        jPanel2.add(cboTipoPlatillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 200, -1));

        btnBuscar.setBackground(new java.awt.Color(86, 73, 64));
        btnBuscar.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setText("Filtrar");
        btnBuscar.setIconTextGap(20);
        btnBuscar.setOpaque(true);
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 360, 50));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 1270, 90));

        btnProcesarPedido.setBackground(new java.awt.Color(86, 73, 64));
        btnProcesarPedido.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btnProcesarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnProcesarPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnProcesarPedido.setText("Procesar Pedido");
        btnProcesarPedido.setIconTextGap(20);
        btnProcesarPedido.setOpaque(true);
        btnProcesarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProcesarPedidoMouseClicked(evt);
            }
        });
        add(btnProcesarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 820, 280, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void tableAlimentosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAlimentosMousePressed
        // TODO add your handling code here:

        TableModel tableModel = tableAlimentos.getModel();
        String codigo = (String) tableModel.getValueAt(tableAlimentos.getSelectedRow(), 0);

        Peticion peticion = new Peticion(TipoAccion.CONSULTAR_PRODUCTO, codigo);
        Client conexion = new Client(peticion);

        Object respuesta = conexion.getRespuestaServer();
        if(respuesta != null){
            if (evt.getClickCount() == 1) {
                cargarCampos((Alimento)respuesta);
            }
        }

    }//GEN-LAST:event_tableAlimentosMousePressed

    private void imgArrowLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgArrowLeftMouseClicked
        // TODO add your handling code here:
        Utilities.cargarPanel(contentPanel, backPanel);
        JPanel ferks = new JPanel();
        ferks.setBackground(new Color(86,73,64));
        Utilities.cargarPanel(usefulPanel,ferks);
    }//GEN-LAST:event_imgArrowLeftMouseClicked

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        TableModel tableModel = tableAlimentos.getModel();
        String codigo = (String) tableModel.getValueAt(tableAlimentos.getSelectedRow(), 0);
        
        Peticion peticion = new Peticion(TipoAccion.CONSULTAR_PRODUCTO, codigo);
        Client conexion = new Client(peticion);
        int cantAgregar =0;
        
        Object respuesta = conexion.getRespuestaServer();
        if(respuesta != null){
            try {
                cantAgregar = Integer.parseInt(txtCantidadAgregar.getText());
                Producto producto = new Producto((Alimento)respuesta, cantAgregar);
                carrito.agregarCarrito(producto);                
                GridBagConstraints gbc = new GridBagConstraints();
                gbc.gridwidth = GridBagConstraints.REMAINDER;
                gbc.weightx = 1;
                gbc.fill = GridBagConstraints.HORIZONTAL;
                carritoPanel.mainList.add(new PanelAlimento(carritoPanel,cantAgregar,(Alimento)respuesta, carrito, producto), gbc, 0);                
                carritoPanel.validate();
                carritoPanel.repaint();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Hay datos Incorrectos!", "Error", JOptionPane.ERROR_MESSAGE);
            } 
            
            
        }
        
        
        
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        String tipo = cboTipoPlatillo.getSelectedItem().toString();
        TVisibilidad visibilidad = null;
        ArrayList datosEntrada = new ArrayList();

        datosEntrada.add("catalogoAlimentos.dat");
        datosEntrada.add(Utilities.convertNameToTPlatillo(tipo));
        datosEntrada.add(visibilidad);
        datosEntrada.add(1);

        Peticion peticion = new Peticion(TipoAccion.VER_PRODUCTOS, datosEntrada);
        Client conexion = new Client(peticion);

        Object respuesta = conexion.getRespuestaServer();
        if(respuesta != null){
            tableAlimentos.setModel((DefaultTableModel)respuesta);
            tableAlimentos.setDefaultEditor(Object.class, null);
        }

    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnProcesarPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProcesarPedidoMouseClicked
        // TODO add your handling code here:
        if(carrito.getCarrito().size() >0){
            Utilities.cargarPanel(contentPanel, pedidoMenuPanel);
        }else{
            JOptionPane.showMessageDialog(null, "Debe agregar Alimentos!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnProcesarPedidoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAgregar;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnProcesarPedido;
    private javax.swing.JComboBox<String> cboTipoPlatillo;
    private javax.swing.JLabel imgAlimento;
    private javax.swing.JLabel imgArrowLeft;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbSismos12;
    private javax.swing.JLabel lbSismos14;
    private javax.swing.JLabel lbSismos15;
    private javax.swing.JLabel lbSismos16;
    private javax.swing.JLabel lbSismos17;
    private javax.swing.JLabel lbSismos18;
    private javax.swing.JLabel lbSismos19;
    private javax.swing.JLabel lbSismos21;
    private javax.swing.JLabel lbSismos22;
    private javax.swing.JTable tableAlimentos;
    private javax.swing.JTextField txtCalorias;
    private javax.swing.JTextField txtCantidadAgregar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPiezas;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSizePorcion;
    // End of variables declaration//GEN-END:variables
}
