/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppCliente.vista;

import javax.swing.JPanel;

/**
 *
 * @author erksm
 */
public class PanelMenuInicial extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuInicial
     */
    private PanelClienteOrdenar clienteOrdenarPanel;
    private PanelCarrito carritoPanel;
    private PanelLogin adminPanel;
    
    private JPanel usefulPanel;
    private JPanel contentPanel;
    private JPanel backPanel;
    public PanelMenuInicial(JPanel useful,JPanel content) {
        initComponents();
        
        usefulPanel = useful;
        contentPanel = content;

        carritoPanel = new PanelCarrito();
        clienteOrdenarPanel = new PanelClienteOrdenar(usefulPanel, contentPanel, this, carritoPanel);
        adminPanel = new PanelLogin(usefulPanel, contentPanel, this);
        
        imgAdmin.setIcon(Utilities.loadResizeIcon("src\\img\\admin.png", 150));
        imgCliente.setIcon(Utilities.loadResizeIcon("src\\img\\cliente.png", 150)); 
        Utilities.cargarPanel(usefulPanel, carritoPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdmin = new javax.swing.JPanel();
        imgAdmin = new javax.swing.JLabel();
        lbSismos13 = new javax.swing.JLabel();
        btnClient = new javax.swing.JPanel();
        imgCliente = new javax.swing.JLabel();
        lbSismos15 = new javax.swing.JLabel();
        lbSismos14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdmin.setBackground(new java.awt.Color(212, 212, 212));
        btnAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminMouseClicked(evt);
            }
        });
        btnAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin.png"))); // NOI18N
        imgAdmin.setToolTipText("");
        imgAdmin.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        imgAdmin.setIconTextGap(2);
        imgAdmin.setPreferredSize(new java.awt.Dimension(500, 500));
        btnAdmin.add(imgAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 150, 150));

        lbSismos13.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos13.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbSismos13.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos13.setText("Admin");
        lbSismos13.setToolTipText("");
        btnAdmin.add(lbSismos13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 70, 40));

        add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 250, 250));

        btnClient.setBackground(new java.awt.Color(212, 212, 212));
        btnClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientMouseClicked(evt);
            }
        });
        btnClient.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin.png"))); // NOI18N
        imgCliente.setToolTipText("");
        imgCliente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        imgCliente.setIconTextGap(2);
        imgCliente.setPreferredSize(new java.awt.Dimension(500, 500));
        btnClient.add(imgCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 150, 150));

        lbSismos15.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos15.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbSismos15.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos15.setText("Cliente");
        lbSismos15.setToolTipText("");
        btnClient.add(lbSismos15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 80, 40));

        add(btnClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 190, 250, 250));

        lbSismos14.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos14.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        lbSismos14.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos14.setText("Choose an option");
        lbSismos14.setToolTipText("");
        add(lbSismos14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 280, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminMouseClicked
        // TODO add your handling code here:

        Utilities.cargarPanel(contentPanel,adminPanel);
    }//GEN-LAST:event_btnAdminMouseClicked

    private void btnClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientMouseClicked
        // TODO add your handling code here:
        Utilities.cargarPanel(contentPanel,clienteOrdenarPanel);
        Utilities.cargarPanel(usefulPanel, carritoPanel);
    }//GEN-LAST:event_btnClientMouseClicked
    
    public void limpiarCarrito(){
//        carritoPanel = new PanelCarrito();
//        Utilities.cargarPanel(usefulPanel, carritoPanel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAdmin;
    private javax.swing.JPanel btnClient;
    private javax.swing.JLabel imgAdmin;
    private javax.swing.JLabel imgCliente;
    private javax.swing.JLabel lbSismos13;
    private javax.swing.JLabel lbSismos14;
    private javax.swing.JLabel lbSismos15;
    // End of variables declaration//GEN-END:variables
}
