/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppCliente.vista;

import AppCliente.conexion.Client;
import general.Peticion;
import general.TipoAccion;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author muril
 */
public class PanelEstadisticaPorcentaje extends javax.swing.JPanel {
    private JPanel contentPanel;
    private JPanel backPanel;

    /**
     * Creates new form PanelEstadisticaPorcentaje
     */
    public PanelEstadisticaPorcentaje(JPanel content, JPanel back) {
        initComponents();
        contentPanel = content; 
        backPanel = back;
        imgExpress.setIcon(Utilities.loadResizeIcon("src\\img\\express.png", 150));        
        imgREcoger.setIcon(Utilities.loadResizeIcon("src\\img\\recoger.png", 150));  
        imgMesa.setIcon(Utilities.loadResizeIcon("src\\img\\mesa.png", 150));
        imgArrowLeft.setIcon(Utilities.loadResizeIcon("src\\img\\arrow-left.png", 50));
    }
    
    public void loadDatos(){        
        Peticion peticion = new Peticion(TipoAccion.PORCENTAJE, "");
        Client conexion = new Client(peticion);     
        
        Object respuesta = conexion.getRespuestaServer();
        if(respuesta != null){
            ArrayList datos = (ArrayList)respuesta;
            lbSitio.setText(String.valueOf((double)datos.get(0))+" %");
            lbExpress.setText(String.valueOf((double)datos.get(1))+" %");
            lbRecoger.setText(String.valueOf((double)datos.get(2))+" %");
        }else{
            System.out.println("La vara es nul");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnSitio = new javax.swing.JPanel();
        imgMesa = new javax.swing.JLabel();
        lbSitio = new javax.swing.JLabel();
        lbSismos19 = new javax.swing.JLabel();
        imgArrowLeft = new javax.swing.JLabel();
        lbSismos14 = new javax.swing.JLabel();
        btnExpress = new javax.swing.JPanel();
        imgExpress = new javax.swing.JLabel();
        lbSismos15 = new javax.swing.JLabel();
        lbExpress = new javax.swing.JLabel();
        btnRecoger = new javax.swing.JPanel();
        imgREcoger = new javax.swing.JLabel();
        lbSismos16 = new javax.swing.JLabel();
        lbRecoger = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSitio.setBackground(new java.awt.Color(212, 212, 212));
        btnSitio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSitioMouseClicked(evt);
            }
        });
        btnSitio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin.png"))); // NOI18N
        imgMesa.setToolTipText("");
        imgMesa.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        imgMesa.setIconTextGap(2);
        imgMesa.setPreferredSize(new java.awt.Dimension(500, 500));
        btnSitio.add(imgMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 150, 150));

        lbSitio.setBackground(new java.awt.Color(0, 0, 0));
        lbSitio.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbSitio.setForeground(new java.awt.Color(0, 0, 0));
        lbSitio.setText("100.0 %");
        lbSitio.setToolTipText("");
        btnSitio.add(lbSitio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 90, 40));

        lbSismos19.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos19.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbSismos19.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos19.setText("En Sitio");
        lbSismos19.setToolTipText("");
        btnSitio.add(lbSismos19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 90, 40));

        jPanel2.add(btnSitio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 360, 290));

        imgArrowLeft.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        imgArrowLeft.setForeground(new java.awt.Color(255, 255, 255));
        imgArrowLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO.png"))); // NOI18N
        imgArrowLeft.setText("<");
        imgArrowLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgArrowLeftMouseClicked(evt);
            }
        });
        jPanel2.add(imgArrowLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        lbSismos14.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos14.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        lbSismos14.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos14.setText("Relación porcentual de pedidos");
        lbSismos14.setToolTipText("");
        jPanel2.add(lbSismos14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 510, 40));

        btnExpress.setBackground(new java.awt.Color(212, 212, 212));
        btnExpress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExpressMouseClicked(evt);
            }
        });
        btnExpress.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgExpress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgExpress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin.png"))); // NOI18N
        imgExpress.setToolTipText("");
        imgExpress.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        imgExpress.setIconTextGap(2);
        imgExpress.setPreferredSize(new java.awt.Dimension(500, 500));
        btnExpress.add(imgExpress, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 150, 150));

        lbSismos15.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos15.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbSismos15.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos15.setText("Express");
        lbSismos15.setToolTipText("");
        btnExpress.add(lbSismos15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 100, 40));

        lbExpress.setBackground(new java.awt.Color(0, 0, 0));
        lbExpress.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbExpress.setForeground(new java.awt.Color(0, 0, 0));
        lbExpress.setText("100.0 %");
        lbExpress.setToolTipText("");
        btnExpress.add(lbExpress, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 100, 40));

        jPanel2.add(btnExpress, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 180, 350, 290));

        btnRecoger.setBackground(new java.awt.Color(212, 212, 212));
        btnRecoger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecogerMouseClicked(evt);
            }
        });
        btnRecoger.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgREcoger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgREcoger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin.png"))); // NOI18N
        imgREcoger.setToolTipText("");
        imgREcoger.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        imgREcoger.setIconTextGap(2);
        imgREcoger.setPreferredSize(new java.awt.Dimension(500, 500));
        btnRecoger.add(imgREcoger, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 150, 150));

        lbSismos16.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos16.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbSismos16.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos16.setText("Recoger");
        lbSismos16.setToolTipText("");
        btnRecoger.add(lbSismos16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 110, 40));

        lbRecoger.setBackground(new java.awt.Color(0, 0, 0));
        lbRecoger.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbRecoger.setForeground(new java.awt.Color(0, 0, 0));
        lbRecoger.setText("100.0 %");
        lbRecoger.setToolTipText("");
        btnRecoger.add(lbRecoger, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 90, 40));

        jPanel2.add(btnRecoger, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 340, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1362, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSitioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSitioMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSitioMouseClicked

    private void btnRecogerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecogerMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnRecogerMouseClicked

    private void btnExpressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExpressMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnExpressMouseClicked

    private void imgArrowLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgArrowLeftMouseClicked
        // TODO add your handling code here:
        Utilities.cargarPanel(contentPanel, backPanel);

    }//GEN-LAST:event_imgArrowLeftMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnExpress;
    private javax.swing.JPanel btnRecoger;
    private javax.swing.JPanel btnSitio;
    private javax.swing.JLabel imgArrowLeft;
    private javax.swing.JLabel imgExpress;
    private javax.swing.JLabel imgMesa;
    private javax.swing.JLabel imgREcoger;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbExpress;
    private javax.swing.JLabel lbRecoger;
    private javax.swing.JLabel lbSismos14;
    private javax.swing.JLabel lbSismos15;
    private javax.swing.JLabel lbSismos16;
    private javax.swing.JLabel lbSismos19;
    private javax.swing.JLabel lbSitio;
    // End of variables declaration//GEN-END:variables
}
