/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppCliente.vista;

import AppCliente.conexion.Client;
import AppServidora.modelo.Carrito;
import AppServidora.modelo.Constantes;
import AppServidora.modelo.PExpress;
import AppServidora.modelo.PMesa;
import general.Peticion;
import general.TipoAccion;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author muril
 */
public class PanelPedidoExpress extends javax.swing.JPanel {

    /**
     * Creates new form PanelPedidoExpress
     */
    
    private PExpress pExpress;
    private Carrito carrito;
    private JPanel contentPanel;
    private JPanel backPanel;
    private JPanel usefulPanel;
    public PanelPedidoExpress(JPanel useful,JPanel content, JPanel back,Carrito carrito) {
        initComponents();        
        this.carrito = carrito;
        usefulPanel = useful;
        contentPanel = content; 
        backPanel = back;
        imgArrowLeft.setIcon(Utilities.loadResizeIcon("src\\img\\arrow-left.png", 50));
    }
    public void loadDatos(String nombre){
        Peticion peticion = new Peticion(TipoAccion.LOAD_CONST,"");
        Client conexion = new Client(peticion);
        Object respuesta = conexion.getRespuestaServer();
        if(respuesta != null){
            ArrayList array = (ArrayList)respuesta;
            Constantes.setContantEmpaque((int)array.get(0));
            Constantes.setContanteEntrega((int)array.get(1));
        }
        Date fecha = new Date(System.currentTimeMillis());        
        pExpress = new PExpress(0,carrito, carrito.getTotalPrecio(),fecha,nombre);
        txtDesgloce.setText(pExpress.mostrarDesgloce());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDesgloce = new javax.swing.JTextArea();
        txtNumeroTel = new javax.swing.JTextField();
        lbSismos13 = new javax.swing.JLabel();
        btnOrdenar = new javax.swing.JLabel();
        lbSismos15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        lbSismos14 = new javax.swing.JLabel();
        imgArrowLeft = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(212, 212, 212));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 340, 10));

        jPanel2.setBackground(new java.awt.Color(86, 73, 64));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDesgloce.setEditable(false);
        txtDesgloce.setBackground(new java.awt.Color(86, 73, 64));
        txtDesgloce.setColumns(20);
        txtDesgloce.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtDesgloce.setForeground(new java.awt.Color(255, 255, 255));
        txtDesgloce.setRows(5);
        txtDesgloce.setText("asdfasdf");
        txtDesgloce.setToolTipText("");
        jScrollPane2.setViewportView(txtDesgloce);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 590, 450));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 630, 500));

        txtNumeroTel.setBackground(new java.awt.Color(212, 212, 212));
        txtNumeroTel.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtNumeroTel.setForeground(new java.awt.Color(99, 99, 99));
        txtNumeroTel.setBorder(null);
        jPanel1.add(txtNumeroTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 340, 30));

        lbSismos13.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos13.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbSismos13.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos13.setText("Dirección exacta");
        lbSismos13.setToolTipText("");
        jPanel1.add(lbSismos13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 140, 30));

        btnOrdenar.setBackground(new java.awt.Color(86, 73, 64));
        btnOrdenar.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btnOrdenar.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdenar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnOrdenar.setText("Ordenar");
        btnOrdenar.setIconTextGap(20);
        btnOrdenar.setOpaque(true);
        btnOrdenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOrdenarMouseClicked(evt);
            }
        });
        jPanel1.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 340, 50));

        lbSismos15.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos15.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbSismos15.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos15.setText("Número de teléfono");
        lbSismos15.setToolTipText("");
        jPanel1.add(lbSismos15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 170, 30));

        txtDireccion.setBackground(new java.awt.Color(212, 212, 212));
        txtDireccion.setColumns(20);
        txtDireccion.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(0, 0, 0));
        txtDireccion.setRows(5);
        txtDireccion.setToolTipText("");
        jScrollPane1.setViewportView(txtDireccion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 530, 200));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 1210, 500));

        lbSismos14.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos14.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        lbSismos14.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos14.setText("Por express");
        lbSismos14.setToolTipText("");
        add(lbSismos14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 200, 40));

        imgArrowLeft.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        imgArrowLeft.setForeground(new java.awt.Color(255, 255, 255));
        imgArrowLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO.png"))); // NOI18N
        imgArrowLeft.setText("<");
        imgArrowLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgArrowLeftMouseClicked(evt);
            }
        });
        add(imgArrowLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrdenarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrdenarMouseClicked
        // TODO add your handling code here:
        String numeroTelefono = "";
        String direccion = "";
        
        try{
            numeroTelefono = txtNumeroTel.getText();
            pExpress.setNúmeroTelefono(numeroTelefono);
            direccion = txtDireccion.getText();
            pExpress.setDireccion(direccion);
            
            
            Peticion peticion = new Peticion(TipoAccion.AGREGAR_PEDIDO, pExpress);
            Client conexion = new Client(peticion);
            Object respuesta = conexion.getRespuestaServer();
            if(respuesta != null){
                if((boolean)respuesta){
                    JOptionPane.showMessageDialog(null, "Se ha registrado su pedido correctamente!", "Error", JOptionPane.INFORMATION_MESSAGE);
                    PanelMenuInicial nuevo = new PanelMenuInicial(usefulPanel, contentPanel);
                    Utilities.cargarPanel(contentPanel, nuevo);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hay datos Incorrectos!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnOrdenarMouseClicked

    private void imgArrowLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgArrowLeftMouseClicked
        // TODO add your handling code here:
        Utilities.cargarPanel(contentPanel, backPanel);
    }//GEN-LAST:event_imgArrowLeftMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnOrdenar;
    private javax.swing.JLabel imgArrowLeft;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbSismos13;
    private javax.swing.JLabel lbSismos14;
    private javax.swing.JLabel lbSismos15;
    private javax.swing.JTextArea txtDesgloce;
    private javax.swing.JTextArea txtDireccion;
    private javax.swing.JTextField txtNumeroTel;
    // End of variables declaration//GEN-END:variables
}
