/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppCliente.vista;

import java.awt.Color;
import javax.swing.JPanel;

import AppCliente.conexion.Client;
import general.Peticion;
import general.TipoAccion;
import javax.swing.JOptionPane;
/**
 *
 * @author erksm
 */
public class PanelLogin extends javax.swing.JPanel {

    /**
     * Creates new form AdminPanel
     */
    private JPanel usefulPanel;
    private JPanel contentPanel;
    private JPanel backPanel;
    private PanelAdminMenu adminPanelMenu;

    public PanelLogin(JPanel useful,JPanel content, JPanel back) {
        initComponents();
        usefulPanel = useful;
        contentPanel = content;
        backPanel = back;
        
        adminPanelMenu = new PanelAdminMenu(usefulPanel,contentPanel,backPanel);
        
        imgLogoF.setIcon(Utilities.loadResizeIcon("src\\img\\logoF.png", 400));
        imgArrowLeft.setIcon(Utilities.loadResizeIcon("src\\img\\arrow-left.png", 50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        imgLogoF = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lbSismos12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JTextField();
        lbSismos13 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JLabel();
        lbSismos14 = new javax.swing.JLabel();
        imgArrowLeft = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        jPanel1.setBackground(new java.awt.Color(212, 212, 212));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 340, 10));

        jPanel2.setBackground(new java.awt.Color(86, 73, 64));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLogoF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLogoF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoF.png"))); // NOI18N
        imgLogoF.setToolTipText("");
        imgLogoF.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        imgLogoF.setIconTextGap(2);
        imgLogoF.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel2.add(imgLogoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 400, 400));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 630, 500));

        txtUsername.setBackground(new java.awt.Color(212, 212, 212));
        txtUsername.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(99, 99, 99));
        txtUsername.setBorder(null);
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 360, 30));

        lbSismos12.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos12.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbSismos12.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos12.setText("Password");
        lbSismos12.setToolTipText("");
        jPanel1.add(lbSismos12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 130, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 340, 10));

        txtPassword.setBackground(new java.awt.Color(212, 212, 212));
        txtPassword.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(99, 99, 99));
        txtPassword.setBorder(null);
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 360, 30));

        lbSismos13.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos13.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbSismos13.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos13.setText("Username");
        lbSismos13.setToolTipText("");
        jPanel1.add(lbSismos13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 130, 30));

        btnLogin.setBackground(new java.awt.Color(86, 73, 64));
        btnLogin.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogin.setText("Login");
        btnLogin.setIconTextGap(20);
        btnLogin.setOpaque(true);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 340, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 1210, 500));

        lbSismos14.setBackground(new java.awt.Color(0, 0, 0));
        lbSismos14.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        lbSismos14.setForeground(new java.awt.Color(0, 0, 0));
        lbSismos14.setText("Login");
        lbSismos14.setToolTipText("");
        add(lbSismos14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 110, 40));

        imgArrowLeft.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        imgArrowLeft.setForeground(new java.awt.Color(255, 255, 255));
        imgArrowLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO.png"))); // NOI18N
        imgArrowLeft.setText("<");
        imgArrowLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgArrowLeftMouseClicked(evt);
            }
        });
        add(imgArrowLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        String user= txtUsername.getText();
        String password= txtPassword.getText();
        
        if(user.equals("") || password.equals("")){
            JOptionPane.showMessageDialog(null, "Debe Ingresar un datos!", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            Peticion peticionIngresar = new Peticion(TipoAccion.INGRESAR, user+"-"+password );
        
            Client conexion = new Client(peticionIngresar);

            boolean respuesta = (boolean) conexion.getRespuestaServer();
            if(respuesta){
               Utilities.cargarPanel(contentPanel, adminPanelMenu);
            }else{
                JOptionPane.showMessageDialog(null, "Los datos no coinciden!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        // se crea una peticion de tipo INGRESAR que devolverá un boolean como respuesta.
        // esto por definición de los servicios provistos por la aplicación servidora
        
        
        
        

        usefulPanel.setBackground(Color.red);
        
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginMouseExited

    private void imgArrowLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgArrowLeftMouseClicked
        // TODO add your handling code here:
        Utilities.cargarPanel(contentPanel, backPanel);

    }//GEN-LAST:event_imgArrowLeftMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel imgArrowLeft;
    private javax.swing.JLabel imgLogoF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbSismos12;
    private javax.swing.JLabel lbSismos13;
    private javax.swing.JLabel lbSismos14;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
